/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-07-12 18:57:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registerNewSystem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Register System For Archival</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<form action=\"submitNewSystemEntry\" method=\"post\">\n");
      out.write("<center>\n");
      out.write("<br><br><br><br><br><br><br><br><br>Register a New System for Archival\n");
      out.write("<table border=\"1\">\n");
      out.write(" \t<tr>\n");
      out.write(" \t\t<td>Select Database Type</td>\n");
      out.write("\t\t<td><input type=\"radio\" name=\"radiogroup\" value=\"rOracle\" checked=\"checked\">Oracle</td>\n");
      out.write("\t\t<td><input type=\"radio\" name=\"radiogroup\" value=\"rTeraData\">TeraData</td>\n");
      out.write("\t\t<td><input type=\"radio\" name=\"radiogroup\" value=\"rmysql\">MySql</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>Host Name:<input type=\"text\" name=\"rHostName\" value=\"\"></td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>Port Number:<input type=\"text\" name=\"rPortNumber\" value=\"\"></td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>Service Name:<input type=\"text\" name=\"rServiceName\" value=\"\"></td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t</tr>\n");
      out.write(" \t<tr>\n");
      out.write("\t\t<td>UserName: <input type=\"text\" name=\"rUsername\" value=\"\"/></td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>Password: <input type=\"text\" name=\"rPassword\" value=\"\"/></td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t</tr> \t\t\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>For Oracle only/JS validation</td>\n");
      out.write("\t\t<td><input type=\"radio\" name=\"radiogroup1\" value=\"clintThin\" checked=\"checked\">JDBC Thin client-side driver</td>\n");
      out.write("\t\t<td><input type=\"radio\" name=\"radiogroup1\" value=\"serverThin\">JDBC Thin server-side driver</td>\n");
      out.write("\t\t<td><input type=\"radio\" name=\"radiogroup1\" value=\"oci\">JDBC OCI client-side driver</td>\n");
      out.write("\t\t<td><input type=\"radio\" name=\"radiogroup1\" value=\"ss\">JDBC Server-Side Internal driver</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td><input type=\"submit\" value=\"Submit\" name=\"submit\">\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t\t<td>&nbsp;</td>\n");
      out.write("\t</tr>\n");
      out.write("</table>\n");
      out.write("\t</center>\n");
      out.write("\t</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
